export { MapleConfigError, validateConfig, validateConfigSync } from "./config/index.js";
export type {
  AnyConnector,
  CapabilityReport,
  ClassifierConnector,
  ClassifierRequest,
  CommentKind,
  CommentPage,
  ConnectorKind,
  ConnectorMeta,
  ConnectorMethod,
  GateConnector,
  GateReport,
  GateTarget,
  GitHubGateOptions,
  IdentityConnector,
  IdentityRequest,
  KindGuess,
  ListQuery,
  MediaConnector,
  ObservabilityConnector,
  Pillar,
  PillarLevel,
  PillarScore,
  ReplayEvent,
  ReplayQuery,
  ScoreRequest,
  StoreConnector,
} from "./connectors/index.js";
export {
  assertUsable,
  capabilitiesOf,
  CHECK_NAME,
  COMMENT_KINDS,
  CONNECTOR_METHODS,
  DEFAULT_PILLARS,
  FALLBACK_KIND,
  githubGate,
  keywordClassifier,
  kindFromWeights,
  MissingCapabilityError,
  missingRequirements,
  REQUIRED_METHODS,
  scoreAtPosition,
  selectPillars,
  supports,
  UnknownPillarError,
} from "./connectors/index.js";
export { MapleStoreError } from "./errors.js";
export { BLOCKING_STATUSES, decideGate } from "./gate/index.js";
export type { GateOptions } from "./gate/index.js";
export { CyclicValueError, stableStringify } from "./lib/stable-stringify.js";
export { consoleSink, createLogger, LEVEL_RANK, memorySink } from "./logger/index.js";
export type {
  LogFields,
  Logger,
  LoggerOptions,
  LogLevel,
  LogRecord,
  LogSink,
  MemorySink,
} from "./logger/index.js";
export { createCommentStore } from "./store.js";
export type { CommentStore } from "./store.js";
export type {
  AnchorRegion,
  Comment,
  CommentAnchor,
  CommentAuthor,
  CommentContext,
  CommentResolution,
  CommentStatus,
  GateConclusion,
  GateReason,
  GateVerdict,
  IdentityProvenance,
  MapleUser,
  MediaBlob,
  MediaRef,
  MediaSource,
  NewComment,
  PickKind,
  RegionContext,
  TextQuote,
} from "./types.js";
